In [1]:
import numpy as np

In [2]:
one_dim=np.array([range(1,11)])
one_dim

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [5]:
two_dim=np.random.rand(3,4)
two_dim

array([[0.79410191, 0.61296994, 0.03564056, 0.98793557],
       [0.52479856, 0.49682932, 0.24815299, 0.21875123],
       [0.74151965, 0.09746382, 0.16404273, 0.05390687]])

In [9]:
zero_arr=np.zeros((2,3,4))
zero_arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
a=np.array([10,100,1000])
b=np.array([11,111,1111])
add_op=a+b
add_op

array([  21,  211, 2111])

In [14]:
sub_op=a-b
sub_op

array([  -1,  -11, -111])

In [15]:
mul_op=a*b
mul_op

array([    110,   11100, 1111000])

In [16]:
divide_op=a/b
divide_op

array([0.90909091, 0.9009009 , 0.90009001])

In [17]:
mean_arr=np.mean(a)
mean_arr

370.0

In [18]:
median_arr=np.median(a)
median_arr

100.0

In [19]:
std_arr=np.std(a)
std_arr

446.9899327725402

In [27]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshape_arr=arr.reshape((3,4))
reshape_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
twod_mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
twod_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
first_row=twod_mat[0]
first_row

array([1, 2, 3])

In [32]:
last_column=twod_mat[:,2]
last_column

array([3, 6, 9])

In [35]:
oned_mat=np.array([1,2,3,4])
reversed_mat=np.flip(oned_mat)
reversed_mat

array([4, 3, 2, 1])

In [43]:
new_2d=np.array([[1,2,3],[4,9,8],[5,6,7]])
condition_mat=new_2d[new_2d%4==0]
condition_mat

array([4, 8])

In [45]:
scalar_value=100
updated_arr=new_2d+scalar_value
updated_arr

array([[101, 102, 103],
       [104, 109, 108],
       [105, 106, 107]])

In [48]:
first_arr=np.array([[1,2,3,4],[9,8,7,6]])
second_arr=np.array([11,22,34,55])
mul_arr=first_arr*second_arr
mul_arr

array([[ 11,  44, 102, 220],
       [ 99, 176, 238, 330]])

In [50]:
arr_one=np.array([11,22,33])
arr_two=np.array([44,55,66])
final_arr=np.dot(arr_one,arr_two)
final_arr

3872

In [55]:
first_2d_arr=np.array([[1,2,3],[3,2,1],[1,1,1]])
second_2d_arr=np.array([[11,22,33],[13,21,12],[10,100,1000]])
matrix_mul=np.matmul(first_2d_arr,second_2d_arr)
matrix_mul

array([[  67,  364, 3057],
       [  69,  208, 1123],
       [  34,  143, 1045]])

In [56]:
inv_arr=np.array([[1,2],[3,4]])
result=np.linalg.inv(inv_arr)
result

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [58]:
final_result=np.linalg.det(inv_arr)
final_result

-2.0000000000000004